application: feed--me
version: 2
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: _go_app
  login: required